// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MountainTrailsSystem.Infrastructure.Data;

#nullable disable

namespace MountainTrailsSystem.Infrastructure.Migrations
{
    [DbContext(typeof(MountainTrailsSystemDbContext))]
    [Migration("20240409220240_UserTrailConstraintAdded")]
    partial class UserTrailConstraintAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ed3483b5-6152-4b74-a0fe-00fc4a0a77a0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0403ab4a-18c4-4bf3-8112-89daaf2364d7",
                            Email = "admin@mts.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MTS.COM",
                            NormalizedUserName = "ADMIN@MTS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEGFpSQnksu0dv0XMQ7Zsl/W2hqGlxbDvyAg9vlLG+Lra8wshXtbzYmmEr1V2vD9afg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bc43523f-4aff-40f6-b350-eb9b94623488",
                            TwoFactorEnabled = false,
                            UserName = "admin@mts.com"
                        });
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Article identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("Article description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the article");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the article is published");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Article title");

                    b.HasKey("ArticleId");

                    b.ToTable("Articles");

                    b.HasComment("News article entity");
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Event identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"), 1L, 1);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)")
                        .HasComment("Event description");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the event ends");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time when the event starts");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Event title");

                    b.HasKey("EventId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Events");

                    b.HasComment("Event entity");
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.Mountain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Mountain identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Mountain name");

                    b.HasKey("Id");

                    b.ToTable("Mountains");

                    b.HasComment("Mountain entity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rila"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pirin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vitosha"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rodopi"
                        });
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.MountainRegion", b =>
                {
                    b.Property<int>("RegionId")
                        .HasColumnType("int")
                        .HasComment("Region identifier");

                    b.Property<int?>("MountainId")
                        .HasColumnType("int")
                        .HasComment("Mountain identifier");

                    b.HasKey("RegionId", "MountainId");

                    b.HasIndex("MountainId");

                    b.ToTable("MountainsRegions");

                    b.HasComment("Connection between mountain and region entities");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            MountainId = 1
                        },
                        new
                        {
                            RegionId = 2,
                            MountainId = 1
                        },
                        new
                        {
                            RegionId = 3,
                            MountainId = 1
                        },
                        new
                        {
                            RegionId = 4,
                            MountainId = 4
                        },
                        new
                        {
                            RegionId = 5,
                            MountainId = 4
                        },
                        new
                        {
                            RegionId = 6,
                            MountainId = 4
                        },
                        new
                        {
                            RegionId = 2,
                            MountainId = 2
                        },
                        new
                        {
                            RegionId = 1,
                            MountainId = 3
                        });
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.Peak", b =>
                {
                    b.Property<int>("PeakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Peak identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeakId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Peak description");

                    b.Property<int>("Elevation")
                        .HasColumnType("int")
                        .HasComment("Peak elevation");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the peak");

                    b.Property<int>("MountainId")
                        .HasColumnType("int")
                        .HasComment("Mountain identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Peak name");

                    b.HasKey("PeakId");

                    b.HasIndex("MountainId");

                    b.ToTable("Peaks");

                    b.HasComment("Mountain peak");

                    b.HasData(
                        new
                        {
                            PeakId = 1,
                            Description = "Ostrets Peak near Velingrad, Bulgaria, boasts stunning natural beauty and panoramic views. Nestled in the Rhodope Mountains, it offers lush forests, hiking trails, and diverse wildlife. Hikers can enjoy reaching the summit for breathtaking vistas of valleys and peaks, making it a favorite for nature lovers.",
                            Elevation = 1369,
                            ImageUrl = "https://www.hotelmap.bg/uploads/images/gallery/fd0f5b5cc57d7316b39a953540707930o5.jpg",
                            MountainId = 4,
                            Name = "Ostrets"
                        },
                        new
                        {
                            PeakId = 2,
                            Description = "Malyovitsa Peak, a striking summit in the Rila Mountains of Bulgaria, is renowned for its dramatic beauty and challenging hiking trails. Surrounded by pristine wilderness, it offers breathtaking views of rugged landscapes and alpine meadows. A favorite destination for outdoor enthusiasts, Malyovitsa Peak provides an unforgettable adventure in the heart of nature.",
                            Elevation = 2729,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Maliovitsa_54072.jpg/1280px-Maliovitsa_54072.jpg",
                            MountainId = 1,
                            Name = "Malyovitsa"
                        },
                        new
                        {
                            PeakId = 3,
                            Description = "Kamenitza Peak, nestled in the Pirin Mountains of Bulgaria, is famed for its majestic beauty and rugged terrain.Trekkers are drawn to its challenging trails and stunning vistas of alpine landscapes.Surrounded by pristine wilderness, Kamenitza Peak offers an exhilarating adventure for nature lovers seeking scenic beauty and outdoor exploration.",
                            Elevation = 2824,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Kamenitsa_Pirin_IMG_2731.jpg/1280px-Kamenitsa_Pirin_IMG_2731.jpg",
                            MountainId = 2,
                            Name = "Kamenitza"
                        },
                        new
                        {
                            PeakId = 4,
                            Description = "Cherni Vrah Peak, the highest point in Vitosha Mountain near Sofia, Bulgaria, offers breathtaking panoramic views and diverse flora and fauna. Popular among hikers, it features well-marked trails and stunning rock formations, providing an unforgettable outdoor experience amidst pristine nature.",
                            Elevation = 2290,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Cherni_Vrah_Vitosha_07.jpg/1280px-Cherni_Vrah_Vitosha_07.jpg",
                            MountainId = 3,
                            Name = "Cherni vrah"
                        });
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Region identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Region name");

                    b.HasKey("RegionId");

                    b.ToTable("Regions");

                    b.HasComment("Region entity");

                    b.HasData(
                        new
                        {
                            RegionId = 1,
                            Name = "Sofia"
                        },
                        new
                        {
                            RegionId = 2,
                            Name = "Blagoevgrad"
                        },
                        new
                        {
                            RegionId = 3,
                            Name = "Kyustendil"
                        },
                        new
                        {
                            RegionId = 4,
                            Name = "Pazardjik"
                        },
                        new
                        {
                            RegionId = 5,
                            Name = "Smolyan"
                        },
                        new
                        {
                            RegionId = 6,
                            Name = "Kardzhali"
                        });
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.Trail", b =>
                {
                    b.Property<int>("TrailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Trail identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrailId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Trail description");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int")
                        .HasComment("Difficulty level of the trail");

                    b.Property<double>("Distance")
                        .HasColumnType("float")
                        .HasComment("Distance of the trail");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time")
                        .HasComment("Duration of the trail");

                    b.Property<int>("ElevationGain")
                        .HasColumnType("int")
                        .HasComment("Elevation gained on the trail");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image URL of the trail");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2")
                        .HasComment("Date and time of last update of the trail's actual state");

                    b.Property<int>("MountainId")
                        .HasColumnType("int")
                        .HasComment("Mountain identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Trail name");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasComment("Rating of the trail");

                    b.Property<int>("RegionId")
                        .HasColumnType("int")
                        .HasComment("Region identifier");

                    b.HasKey("TrailId");

                    b.HasIndex("MountainId");

                    b.HasIndex("RegionId");

                    b.ToTable("Trails");

                    b.HasComment("Mountain trail");

                    b.HasData(
                        new
                        {
                            TrailId = 1,
                            Description = "The trail from Velingrad to Ostrets Peak winds through the picturesque Rhodope Mountains, offering a captivating journey for nature enthusiasts. Beginning in the charming town of Velingrad, known for its mineral springs, the trail gradually ascends through lush forests and meandering streams. As hikers ascend, they are treated to breathtaking vistas of the surrounding valleys and peaks. Along the way, diverse flora and fauna dot the landscape, providing ample opportunities for birdwatching and wildlife spotting. The trail is well-marked and relatively moderate in difficulty, making it accessible to hikers of varying skill levels. Upon reaching Ostrets Peak, adventurers are rewarded with panoramic views that stretch as far as the eye can see, making the journey from Velingrad a truly unforgettable experience in the heart of nature.",
                            DifficultyLevel = 1,
                            Distance = 7.5,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            ElevationGain = 600,
                            ImageUrl = "https://www.hotelmap.bg/uploads/images/gallery/2aab94d31ff1c1a83feec06c3bb722b9o2.jpg",
                            LastUpdated = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MountainId = 4,
                            Name = "Velingrad - Ostrets peak",
                            Rating = 0,
                            RegionId = 4
                        },
                        new
                        {
                            TrailId = 2,
                            Description = "The trail from Sveta Petka to Ostrets Peak offers a captivating journey through the scenic beauty of the Rhodope Mountains in Bulgaria. Starting at the quaint village of Sveta Petka, the trail meanders through lush forests, tranquil meadows, and rocky terrain. Along the way, hikers are treated to panoramic views of the surrounding valleys and peaks, providing ample opportunities for photography and contemplation. The trail is well-maintained but can be challenging in parts, with steep ascents and descents. However, the effort is rewarded with the stunning natural landscapes and the sense of accomplishment upon reaching Ostrets Peak. At the summit, adventurers are greeted with breathtaking vistas that stretch as far as the eye can see, making the journey from Sveta Petka an unforgettable outdoor experience.",
                            DifficultyLevel = 0,
                            Distance = 5.2000000000000002,
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            ElevationGain = 360,
                            ImageUrl = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjZbKuVC8Wp7jV29Wl2FBZABOq87KP5S9W1ot5Q-keCnleh31N3MtM1HottF4hvKvHjnUN8_n8evU_TFEMevjoxPMuIlNDjC_mKbdaPHnMzxJ1Hz4edohwFMoxpXf0Y5eLTx06WADZ0sE0/s1600/22.jpg",
                            LastUpdated = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MountainId = 4,
                            Name = "Sveta Petka Village - Ostrets peak",
                            Rating = 0,
                            RegionId = 4
                        },
                        new
                        {
                            TrailId = 3,
                            Description = "The trail from Malyovitsa Hut to Malyovitsa Peak in the Rila Mountains of Bulgaria offers a captivating adventure amidst stunning alpine scenery. Beginning at the cozy Malyovitsa Hut, nestled in a picturesque valley, the trail ascends gradually through dense forests and rocky slopes. Along the way, hikers are treated to breathtaking views of towering peaks and rugged landscapes. The trail is well-marked and relatively moderate in difficulty, making it accessible to hikers of varying skill levels. As the ascent continues, the scenery becomes increasingly dramatic, with jagged cliffs and cascading waterfalls adding to the allure of the surroundings. Finally, upon reaching the summit of Malyovitsa Peak, adventurers are rewarded with panoramic vistas that stretch as far as the eye can see, offering a sense of accomplishment and awe-inspiring beauty. Whether it's the challenge of the hike or the beauty of the natural surroundings, the trail from Malyovitsa Hut to Malyovitsa Peak promises an unforgettable outdoor experience in the heart of the Rila Mountains.",
                            DifficultyLevel = 3,
                            Distance = 8.0999999999999996,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            ElevationGain = 860,
                            ImageUrl = "https://tripsjournal.com/wp-content/uploads/2017/09/11-vryh-malyovitsa.jpg",
                            LastUpdated = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MountainId = 1,
                            Name = "Malyovitsa hut - Malyovitsa peak",
                            Rating = 0,
                            RegionId = 1
                        },
                        new
                        {
                            TrailId = 4,
                            Description = "The trail from Ivan Vazov Hut to Malyovitsa Peak in Bulgaria's Rila Mountains offers a thrilling journey through diverse landscapes. Starting at the charming Ivan Vazov Hut, nestled amidst lush forests, the trail gradually ascends through alpine meadows and rocky terrain. Hikers are treated to breathtaking views of towering peaks and serene valleys along the way. The trail is well-marked but can be challenging, with steep sections demanding endurance and agility. As the ascent progresses, the scenery becomes increasingly dramatic, with rugged cliffs and cascading streams adding to the allure. Upon reaching the summit of Malyovitsa Peak, adventurers are rewarded with awe-inspiring vistas stretching as far as the eye can see. Whether seeking adventure or tranquility, the trail from Ivan Vazov Hut to Malyovitsa Peak promises an unforgettable outdoor experience amidst the natural splendor of the Rila Mountains.",
                            DifficultyLevel = 3,
                            Distance = 10.300000000000001,
                            Duration = new TimeSpan(0, 4, 30, 0, 0),
                            ElevationGain = 770,
                            ImageUrl = "https://tabakoff.eu/wp/wp-content/uploads/2016/09/DSC_0063.jpg",
                            LastUpdated = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MountainId = 1,
                            Name = "Ivan Vazov hut - Malyovitsa peak",
                            Rating = 0,
                            RegionId = 1
                        },
                        new
                        {
                            TrailId = 5,
                            Description = "The trail from Rila Monastery to Malyovitsa Peak offers a captivating journey through the stunning landscapes of the Rila Mountains in Bulgaria. Beginning at the historic Rila Monastery, a UNESCO World Heritage site, the trail winds through picturesque valleys and dense forests, providing glimpses of cultural and natural heritage along the way. As hikers ascend, the scenery transitions to alpine meadows and rocky slopes, with panoramic views of majestic peaks unfolding before them. The trail is well-marked but challenging, with steep sections demanding endurance and determination. However, the effort is rewarded with breathtaking vistas of the surrounding wilderness and the sense of accomplishment upon reaching Malyovitsa Peak. At the summit, adventurers are greeted with sweeping panoramas that showcase the beauty and grandeur of the Rila Mountains. Whether seeking adventure or spiritual rejuvenation, the trail from Rila Monastery to Malyovitsa Peak promises an unforgettable outdoor experience immersed in the natural splendor of Bulgaria's mountainous landscape.",
                            DifficultyLevel = 4,
                            Distance = 12.199999999999999,
                            Duration = new TimeSpan(0, 6, 0, 0, 0),
                            ElevationGain = 1500,
                            ImageUrl = "https://iskamdaletya.com/wp-content/uploads/2018/08/IMG_5475_edited-e1535716578693.jpg",
                            LastUpdated = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MountainId = 1,
                            Name = "Rila Monastery - Malyovitsa peak",
                            Rating = 0,
                            RegionId = 3
                        },
                        new
                        {
                            TrailId = 6,
                            Description = "The trail from Tevno Ezero Shelter to Kamenitza Peak in Bulgaria's Pirin Mountains offers a captivating journey through pristine alpine scenery. Starting at the tranquil Tevno Ezero Shelter, nestled beside a picturesque lake, the trail leads hikers through dense forests and meandering streams. As the ascent begins, the landscape transforms into rocky terrain, dotted with vibrant alpine flora. The trail is well-marked but challenging, with steep sections demanding endurance and careful footing. Along the way, hikers are rewarded with breathtaking views of jagged peaks and serene valleys, providing ample opportunities for photography and reflection. As the trail nears Kamenitza Peak, the scenery becomes increasingly dramatic, with towering cliffs and rugged ridges dominating the horizon. Upon reaching the summit, adventurers are greeted with panoramic vistas that stretch as far as the eye can see, offering a sense of accomplishment and awe-inspiring beauty. Whether seeking adventure or tranquility, the trail from Tevno Ezero Shelter to Kamenitza Peak promises an unforgettable outdoor experience amidst the natural splendor of the Pirin Mountains.",
                            DifficultyLevel = 3,
                            Distance = 6.4000000000000004,
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            ElevationGain = 600,
                            ImageUrl = "https://bulgarian-photography.com/UserFiles/pictures/BACEEBE3-8BA4-C931-9AE6-A95F97110DCD.jpg",
                            LastUpdated = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MountainId = 2,
                            Name = "Tevno ezero shelter - Kamenitza peak",
                            Rating = 0,
                            RegionId = 2
                        },
                        new
                        {
                            TrailId = 7,
                            Description = "The trail from Begovitsa Hut to Kamenitza Peak in Bulgaria's Pirin Mountains is a breathtaking journey through pristine wilderness. Beginning at the charming Begovitsa Hut, nestled amidst lush forests and meadows, the trail gradually ascends through diverse landscapes. Hikers traverse winding paths, crossing crystal-clear streams and ascending rocky slopes. Along the way, the scenery unfolds in a symphony of colors, with vibrant alpine flora lining the trail. The route is well-marked but challenging, with steep sections requiring careful navigation. As hikers ascend, panoramic vistas of towering peaks and deep valleys reward their efforts. Approaching Kamenitza Peak, the landscape becomes increasingly dramatic, with rugged cliffs and rocky outcrops dominating the skyline. At the summit, adventurers are greeted with awe-inspiring views that stretch as far as the eye can see, providing a sense of accomplishment and connection with nature. Whether seeking adventure or tranquility, the trail from Begovitsa Hut to Kamenitza Peak promises an unforgettable outdoor experience amidst the natural splendor of the Pirin Mountains.",
                            DifficultyLevel = 1,
                            Distance = 8.0999999999999996,
                            Duration = new TimeSpan(0, 3, 30, 0, 0),
                            ElevationGain = 1000,
                            ImageUrl = "https://qbylkovcvqt.blog.bg/photos/31305/552.JPG",
                            LastUpdated = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MountainId = 2,
                            Name = "Begovitsa hut - Kamenitza peak",
                            Rating = 0,
                            RegionId = 2
                        },
                        new
                        {
                            TrailId = 8,
                            Description = "The trail from Bezbog Hut to Kamenitza Peak in Bulgaria's Pirin Mountains offers an exhilarating adventure through stunning alpine landscapes. Beginning at Bezbog Hut, nestled amid picturesque meadows and forests, the trail ascends gradually, revealing panoramic vistas of rugged peaks and deep valleys. Hikers traverse diverse terrain, from lush forests to rocky slopes, with occasional glimpses of pristine alpine lakes. The well-marked trail presents moderate challenges, with some steep sections requiring careful footing. Along the way, hikers are rewarded with sightings of diverse flora and fauna, adding to the allure of the journey. As the ascent progresses, the scenery becomes increasingly dramatic, with towering cliffs and jagged ridges dominating the horizon. Approaching Kamenitza Peak, the trail offers breathtaking views of the surrounding wilderness, culminating in a sense of accomplishment upon reaching the summit. At the peak, adventurers are treated to awe-inspiring vistas that stretch as far as the eye can see, providing a memorable conclusion to the outdoor experience. Whether seeking adventure or tranquility, the trail from Bezbog Hut to Kamenitza Peak promises an unforgettable journey through the natural splendor of the Pirin Mountains.",
                            DifficultyLevel = 3,
                            Distance = 10.6,
                            Duration = new TimeSpan(0, 5, 30, 0, 0),
                            ElevationGain = 930,
                            ImageUrl = "https://kostadinnikolov.com/wp-content/uploads/2020/10/IMG_20200829_111234.jpg",
                            LastUpdated = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MountainId = 2,
                            Name = "Bezbog hut - Kamenitza peak",
                            Rating = 0,
                            RegionId = 2
                        },
                        new
                        {
                            TrailId = 9,
                            Description = "The trail from Aleko Hut to Cherni Vrah Peak in Bulgaria's Vitosha Mountain offers a thrilling adventure through diverse landscapes. Starting at Aleko Hut, nestled amidst lush forests and meadows, the trail ascends steadily, providing stunning views of the surrounding valleys and peaks. Hikers navigate well-marked paths, passing through rocky terrain and alpine meadows adorned with colorful wildflowers. The trail presents moderate challenges, with occasional steep sections requiring careful footing. Along the way, hikers encounter unique flora and fauna, adding to the charm of the journey. As the ascent progresses, the scenery becomes increasingly dramatic, with rocky outcrops and rugged cliffs dominating the landscape. Approaching Cherni Vrah Peak, the trail offers breathtaking panoramas of the surrounding wilderness, culminating in a sense of accomplishment upon reaching the summit. At the peak, adventurers are rewarded with awe-inspiring vistas that stretch as far as the eye can see, providing a memorable conclusion to the outdoor experience. Whether seeking adventure or tranquility, the trail from Aleko Hut to Cherni Vrah Peak promises an unforgettable journey through the natural beauty of Vitosha Mountain.",
                            DifficultyLevel = 0,
                            Distance = 2.8999999999999999,
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            ElevationGain = 480,
                            ImageUrl = "https://tripsjournal.com/wp-content/uploads/2016/03/cherni-vrah.jpg",
                            LastUpdated = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MountainId = 3,
                            Name = "Aleko hut - Cherni vrah peak",
                            Rating = 0,
                            RegionId = 1
                        },
                        new
                        {
                            TrailId = 10,
                            Description = "The trail from Zheleznitsa to Cherni Vrah Peak in Bulgaria's Vitosha Mountain offers an exhilarating hike through diverse landscapes. Beginning in the charming village of Zheleznitsa, the trail winds through lush forests and meadows, gradually ascending towards the summit. Hikers traverse well-marked paths, encountering rocky terrain and alpine flora along the way. The trail presents moderate challenges, with some steep sections demanding careful navigation. As the ascent continues, the scenery becomes increasingly dramatic, with panoramic views of the surrounding valleys and peaks unfolding before hikers' eyes. Approaching Cherni Vrah Peak, the trail offers breathtaking vistas of the rugged landscape, culminating in a sense of achievement upon reaching the summit. At the peak, adventurers are treated to sweeping panoramas that stretch as far as the eye can see, providing a memorable conclusion to the hike. Whether seeking adventure or tranquility, the trail from Zheleznitsa to Cherni Vrah Peak promises an unforgettable outdoor experience immersed in the natural beauty of Vitosha Mountain.",
                            DifficultyLevel = 3,
                            Distance = 9.9000000000000004,
                            Duration = new TimeSpan(0, 4, 30, 0, 0),
                            ElevationGain = 1320,
                            ImageUrl = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiB8-MfRFKr_g1aXDIFhZWC16NwDeeETLTmq3tVFua_qUCUnaRR0J4I-SN2AM9eLl6rdmXNgVQ30Zu1jix7zRIbmjpyFsWyQhBKnxMzM0QwgHo8MG2xeQ4AilpPUMVbNrH3r0Vr-4wZaVc/s1600/1.jpg",
                            LastUpdated = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MountainId = 3,
                            Name = "Zheleznitsa - Cherni vrah peak",
                            Rating = 0,
                            RegionId = 1
                        },
                        new
                        {
                            TrailId = 11,
                            Description = "The trail from Zlatnite Mostove (The Golden Bridges) to Cherni Vrah Peak in Bulgaria's Vitosha Mountain is a breathtaking journey through rugged terrain and stunning vistas. Beginning at the iconic Golden Bridges, where massive rock formations span a mountain river, the trail winds through lush forests and rocky slopes. Hikers traverse well-marked paths, encountering diverse flora and fauna along the way. The trail presents moderate challenges, with occasional steep sections demanding careful footing. As the ascent progresses, the scenery becomes increasingly dramatic, with panoramic views of the surrounding valleys and peaks unfolding before hikers' eyes. Approaching Cherni Vrah Peak, the trail offers awe-inspiring vistas of the rugged landscape, culminating in a sense of achievement upon reaching the summit. At the peak, adventurers are rewarded with sweeping panoramas that stretch as far as the eye can see, providing a memorable conclusion to the hike. Whether seeking adventure or tranquility, the trail from Zlatnite Mostove to Cherni Vrah Peak promises an unforgettable outdoor experience immersed in the natural beauty of Vitosha Mountain.",
                            DifficultyLevel = 1,
                            Distance = 6.4000000000000004,
                            Duration = new TimeSpan(0, 2, 50, 0, 0),
                            ElevationGain = 800,
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/E3_%D0%97%D0%BB%D0%B0%D1%82%D0%BD%D0%B8%D1%82%D0%B5_%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D0%B2%D0%B5.jpg/1280px-E3_%D0%97%D0%BB%D0%B0%D1%82%D0%BD%D0%B8%D1%82%D0%B5_%D0%BC%D0%BE%D1%81%D1%82%D0%BE%D0%B2%D0%B5.jpg",
                            LastUpdated = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MountainId = 3,
                            Name = "Zlatnite mostove - Cherni vrah peak",
                            Rating = 0,
                            RegionId = 1
                        });
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.TrailPeak", b =>
                {
                    b.Property<int>("TrailId")
                        .HasColumnType("int")
                        .HasComment("Trail identifier");

                    b.Property<int?>("PeakId")
                        .HasColumnType("int")
                        .HasComment("Peak identifier");

                    b.HasKey("TrailId", "PeakId");

                    b.HasIndex("PeakId");

                    b.ToTable("TrailsPeaks");

                    b.HasComment("Connection between trail and peak entities");

                    b.HasData(
                        new
                        {
                            TrailId = 1,
                            PeakId = 1
                        },
                        new
                        {
                            TrailId = 2,
                            PeakId = 1
                        },
                        new
                        {
                            TrailId = 3,
                            PeakId = 2
                        },
                        new
                        {
                            TrailId = 4,
                            PeakId = 2
                        },
                        new
                        {
                            TrailId = 5,
                            PeakId = 2
                        },
                        new
                        {
                            TrailId = 6,
                            PeakId = 3
                        },
                        new
                        {
                            TrailId = 7,
                            PeakId = 3
                        },
                        new
                        {
                            TrailId = 8,
                            PeakId = 3
                        },
                        new
                        {
                            TrailId = 9,
                            PeakId = 4
                        },
                        new
                        {
                            TrailId = 10,
                            PeakId = 4
                        },
                        new
                        {
                            TrailId = 11,
                            PeakId = 4
                        });
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.TrailStatusNote", b =>
                {
                    b.Property<int>("TrailStatusNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("TrailStatusNote identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrailStatusNoteId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Description of the updated trail status");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Image verifying the updated trail status");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit")
                        .HasComment("Flag showing if the given note is resolved");

                    b.Property<int>("TrailId")
                        .HasColumnType("int")
                        .HasComment("Trail identifier");

                    b.HasKey("TrailStatusNoteId");

                    b.HasIndex("TrailId");

                    b.ToTable("TrailStatusNotes");

                    b.HasComment("Request for update of the trail status");
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.UserTrail", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User identifier");

                    b.Property<int>("TrailId")
                        .HasColumnType("int")
                        .HasComment("Trail identifier");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("bit")
                        .HasComment("Is trail saved by user");

                    b.Property<bool>("IsVisited")
                        .HasColumnType("bit")
                        .HasComment("Is trail visited by user");

                    b.HasKey("UserId", "TrailId");

                    b.HasIndex("TrailId");

                    b.ToTable("UsersTrails");

                    b.HasComment("Connection between ApplicationUser and Trail entities");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.Event", b =>
                {
                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.ApplicationUser", null)
                        .WithMany("EventsToAttend")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.MountainRegion", b =>
                {
                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.Mountain", "Mountain")
                        .WithMany("Regions")
                        .HasForeignKey("MountainId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.Region", "Region")
                        .WithMany("Mountains")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mountain");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.Peak", b =>
                {
                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.Mountain", "Mountain")
                        .WithMany("Peaks")
                        .HasForeignKey("MountainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mountain");
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.Trail", b =>
                {
                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.Mountain", "Mountain")
                        .WithMany("Trails")
                        .HasForeignKey("MountainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mountain");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.TrailPeak", b =>
                {
                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.Peak", "Peak")
                        .WithMany("Trails")
                        .HasForeignKey("PeakId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.Trail", "Trail")
                        .WithMany("Peaks")
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Peak");

                    b.Navigation("Trail");
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.TrailStatusNote", b =>
                {
                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.Trail", "Trail")
                        .WithMany()
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trail");
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.UserTrail", b =>
                {
                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.Trail", "Trail")
                        .WithMany()
                        .HasForeignKey("TrailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MountainTrailsSystem.Infrastructure.Data.Models.ApplicationUser", "User")
                        .WithMany("SavedVisitedTrails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("EventsToAttend");

                    b.Navigation("SavedVisitedTrails");
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.Mountain", b =>
                {
                    b.Navigation("Peaks");

                    b.Navigation("Regions");

                    b.Navigation("Trails");
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.Peak", b =>
                {
                    b.Navigation("Trails");
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.Region", b =>
                {
                    b.Navigation("Mountains");
                });

            modelBuilder.Entity("MountainTrailsSystem.Infrastructure.Data.Models.Trail", b =>
                {
                    b.Navigation("Peaks");
                });
#pragma warning restore 612, 618
        }
    }
}
